apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  labels:
    app: flask-app
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80 # Service port (what clients connect to)
      targetPort: 5000 # Container port
  type: LoadBalancer # Exposes the service externally using a cloud load balancer
                     # For local testing (e.g., Minikube), you might use NodePort:
                     # type: NodePort