apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce # Can be mounted by a single node
  resources:
    requests:
      storage: 5Gi # Request 5 GB of storage